### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'norm_first'

### ISSUE THREAD

**Issue by AlvaroBeiro** [facebookresearch/demucs#421]
I get this error when trying the new htdemucs with demucs 4.0.0

(demucs) C:\Users\Admin>demucs -n htdemucs D:\input.wav
Traceback (most recent call last):
  File "d:\programas\anaconda\envs\demucs\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\programas\anaconda\envs\demucs\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Programas\Anaconda\envs\demucs\Scripts\demucs.exe\__main__.py", line 7, in <module>
  File "d:\programas\anaconda\envs\demucs\lib\site-packages\demucs\separate.py", line 121, in main
    model = get_model_from_args(args)
  File "d:\programas\anaconda\envs\demucs\lib\site-packages\demucs\pretrained.py", line 89, in get_model_from_args
    return get_model(name=args.name, repo=args.repo)
  File "d:\programas\anaconda\envs\demucs\lib\site-packages\demucs\pretrained.py", line 74, in get_model
    model = any_repo.get_model(name)
  File "d:\programas\anaconda\envs\demucs\lib\site-packages\demucs\repo.py", line 148, in get_model
    return self.bag_repo.get_model(name_or_sig)
  File "d:\programas\anaconda\envs\demucs\lib\site-packages\demucs\repo.py", line 130, in get_model
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "d:\programas\anaconda\envs\demucs\lib\site-packages\demucs\repo.py", line 130, in <listcomp>
    models = [self.model_repo.get_model(sig) for sig in signatures]
  File "d:\programas\anaconda\envs\demucs\lib\site-packages\demucs\repo.py", line 67, in get_model
    return load_model(pkg)
  File "d:\programas\anaconda\envs\demucs\lib\site-packages\demucs\states.py", line 62, in load_model
    model = klass(*args, **kwargs)
  File "d:\programas\anaconda\envs\demucs\lib\site-packages\demucs\states.py", line 146, in __init__
    init(self, *args, **kwargs)
  File "d:\programas\anaconda\envs\demucs\lib\site-packages\demucs\htdemucs.py", line 384, in __init__
    self.crosstransformer = CrossTransformerEncoder(
  File "d:\programas\anaconda\envs\demucs\lib\site-packages\demucs\transformer.py", line 636, in __init__
    self.layers.append(MyTransformerEncoderLayer(**kwargs_classic_encoder))
  File "d:\programas\anaconda\envs\demucs\lib\site-packages\demucs\transformer.py", line 297, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'norm_first'

**Comment by HENDRIX-ZT2** [comment]
Same on my end, just installed via pip.

**Comment by MrBasssman65** [comment]
Also have this same issue.  Recently upgraded Demucs to version 4.0

**Comment by HENDRIX-ZT2** [comment]
Yes, it's working with torch 1.13.1. So the version in requirements.txt should be increased to when that argument was added to torch.

**Comment by MrBasssman65** [comment]
Thank you for your reply.  My knowledge about things related to command lines is quite limited.  I will try to update and see what happens.
________________________________

**Comment by MrBasssman65** [comment]
Would you be kind enough to tell this newbie the command line for installing this new version?
________________________________

**Comment by HENDRIX-ZT2** [comment]
> Would you be kind enough to tell this newbie the command line for installing this new version?
> […](#)
> ________________________________ From: HENDRIX-ZT2 ***@***.***> Sent: Monday, December 19, 2022 5:11 AM To: facebookresearch/demucs ***@***.***> Cc: MrBasssman65 ***@***.***>; Comment ***@***.***> Subject: Re: [facebookresearch/demucs] TypeError: __init__() got an unexpected keyword argument 'norm_first' (Issue #421) Yes, it's working with torch 1.13.1. So the version in requirements.txt should be increased to when that argument was added to torch. — Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffacebookresearch%2Fdemucs%2Fissues%2F421%23issuecomment-1357646572&data=05%7C01%7C%7C9c42c255ec0241b2cce708dae1c28047%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638070522730217933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4e2hNgcg6fbZKUaUAdco%2FISsIyEeqiZARzQwDe6jRSI%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANNVBGAHWXB2ZKMFVWDXCUTWOBNG7ANCNFSM6AAAAAAS2IPNWI&data=05%7C01%7C%7C9c42c255ec0241b2cce708dae1c28047%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638070522730217933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=T16Q2Ze%2Fpxhvz66M8h%2Figdcscft9IJblpozfhTgrrhc%3D&reserved=0>. You are receiving this because you commented.Message ID: ***@***.***>
Go here and then pick the right versions for your system to get the right command:
https://pytorch.org/

**Comment by AlvaroBeiro** [comment]
I think it would be easier to just open an Anaconda prompt and type:

`pip install -U torch torchaudio`

That fixed it for me

**Comment by MrBasssman65** [comment]
Thank you for your response.  I did finally find a way to update pytorch to 1.13.1 and then had to update ffmpeg and torchaudio for use in the same environment.  Not easy when you don't know a lot about python and command line structures haha.  At any rate, I was able to get it to work after all that.  Again, thank you.
________________________________
